apiVersion: batch/v1
kind: Job
metadata:
  name: save-code
  namespace: 6854edf0-186d-4d5e-ac4b-2feb4efe3c7d
spec:
  template:
    spec:
      initContainers:
      - name: get-templates
        image: alpine/git
        env:
          - name: GIT_URL
            value: github.com/appsec-digital/labs.git
          - name: GIT_BRANCH
            value: main
          - name: GIT_PATH
            value: lab-example
          - name: GIT_USERNAME
            value: vitor-mauricio
          - name: GIT_PASSWORD
            value: {pat}
        command: ["sh", "-c", "set -e; echo 'Cloning lab...'; git clone --depth 1 --branch $GIT_BRANCH https://$GIT_USERNAME:$GIT_PASSWORD@$GIT_URL /tmp/lab; echo 'Copying exploit templates...'; cp -r /tmp/lab/$GIT_PATH/* /code; echo 'Chowning lab...'; chown -R 1000:1000 /code"]
        volumeMounts:
        - name: original-code
          mountPath: /code
      containers:
      - name: save-code
        image: ghcr.io/appsec-digital/eval-save-code:dev 
        command: ["/bin/sh", "-c"]
        args:
          - "diff -ruN /code /workspace || true"
        volumeMounts:
        - name: lab-code
          mountPath: /workspace
        - name: original-code
          mountPath: /code
      restartPolicy: Never
      volumes:
      - name: lab-code
        persistentVolumeClaim:
          claimName: code-server-pvc
      - name: original-code
        emptyDir: {}

