apiVersion: batch/v1
kind: Job
metadata:
  name: avaliar-exploit
  namespace: ide-user
spec:
  template:
    spec:
      initContainers:
      - name: get-templates
        image: alpine/git
        env:
          - name: GIT_URL
            value: github.com/appsec-digital/labs.git
          - name: GIT_BRANCH
            value: main
          - name: GIT_PATH
            value: copy-n-paste/scripts/exploit-templates
          - name: GIT_USERNAME
            value: vitor-mauricio
          - name: GIT_PASSWORD
            value: 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
        command: ["sh", "-c", "set -e; echo 'Cloning lab...'; git clone --depth 1 --branch $GIT_BRANCH https://$GIT_USERNAME:$GIT_PASSWORD@$GIT_URL /tmp/lab; echo 'Copying exploit templates...'; cp -r /tmp/lab/$GIT_PATH/* /template; echo 'Chowning lab...'; chown -R 1000:1000 /template"]
        volumeMounts:
        - name: template-volume
          mountPath: /template
      containers:
      - name: exploit
        image: ghcr.io/appsec-digital/eval-exploit:dev
        securityContext:
          privileged: true
        args:
          - "python" 
          - "/app/evaluate.py"
          - "/workspace"
          - "/template"
          - "http://localhost:3000"
        volumeMounts:
        - name: lab-code
          mountPath: /workspace
        - name: template-volume
          mountPath: /template
      restartPolicy: Never
      volumes:
      - name: lab-code
        persistentVolumeClaim:
          claimName: code-volume
      - name: template-volume
        emptyDir: {}

