apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: appseclabs-cluster
  region: sa-east-1

nodeGroups:
  - name: ng-appseclabs
    instanceType: t3.small
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true
