-- Seed Technologies
INSERT INTO technologies (name, description) VALUES
('Docker', 'Containerization platform for building, shipping, and running applications'),
('Kubernetes', 'Container orchestration platform for automating deployment, scaling, and management'),
('React', 'JavaScript library for building user interfaces'),
('Node.js', 'JavaScript runtime built on Chrome''s V8 JavaScript engine'),
('Express.js', 'Fast, unopinionated, minimalist web framework for Node.js'),
('PostgreSQL', 'Open source object-relational database system'),
('MongoDB', 'Document-oriented NoSQL database'),
('Redis', 'In-memory data structure store used as database, cache, and message broker'),
('JWT', 'JSON Web Token for securely transmitting information between parties'),
('OAuth', 'Open standard for access delegation'),
('Spring Boot', 'Java-based framework for creating microservices'),
('Django', 'High-level Python web framework'),
('Flask', 'Lightweight Python web framework'),
('Laravel', 'PHP web application framework'),
('Angular', 'TypeScript-based web application framework'),
('Vue.js', 'Progressive JavaScript framework for building user interfaces'),
('MySQL', 'Open-source relational database management system'),
('Apache', 'Open-source HTTP server'),
('Nginx', 'Web server and reverse proxy server'),
('GraphQL', 'Query language for APIs and runtime for executing queries'),
('REST API', 'Architectural style for designing networked applications'),
('AWS', 'Amazon Web Services cloud computing platform'),
('Azure', 'Microsoft cloud computing platform'),
('GCP', 'Google Cloud Platform'),
('Terraform', 'Infrastructure as code tool'),
('Jenkins', 'Open source automation server for CI/CD'),
('Git', 'Distributed version control system'),
('Elasticsearch', 'Search and analytics engine'),
('RabbitMQ', 'Message broker software'),
('Apache Kafka', 'Distributed streaming platform');

-- Seed Languages
INSERT INTO languages (name) VALUES
('JavaScript'),
('TypeScript'),
('Python'),
('Java'),
('C#'),
('PHP'),
('Go'),
('Rust'),
('Ruby'),
('C++'),
('C'),
('Swift'),
('Kotlin'),
('Scala'),
('R'),
('MATLAB'),
('Perl'),
('Shell/Bash'),
('PowerShell'),
('SQL'),
('HTML'),
('CSS'),
('Dart'),
('Elixir'),
('Haskell'),
('Lua'),
('Objective-C'),
('F#'),
('Clojure'),
('Groovy');

-- Seed Vulnerabilities
INSERT INTO vulnerabilities (name, owasp_reference, description) VALUES
('SQL Injection', 'A03:2021', 'Injection flaws occur when untrusted data is sent to an interpreter as part of a command or query'),
('Cross-Site Scripting (XSS)', 'A07:2021', 'XSS flaws occur when an application includes untrusted data in a web page without proper validation'),
('Cross-Site Request Forgery (CSRF)', 'A01:2021', 'CSRF attacks force an end user to execute unwanted actions on a web application'),
('Insecure Direct Object References', 'A01:2021', 'Direct object references occur when a developer exposes internal implementation objects'),
('Security Misconfiguration', 'A05:2021', 'Security misconfiguration is commonly a result of insecure default configurations'),
('Sensitive Data Exposure', 'A02:2021', 'Failure to adequately protect sensitive data such as financial, healthcare, and PII'),
('Missing Function Level Access Control', 'A01:2021', 'Most web applications verify function level access rights before making functionality visible'),
('Using Components with Known Vulnerabilities', 'A06:2021', 'Components run with the same privileges as the application'),
('Unvalidated Redirects and Forwards', 'A10:2017', 'Web applications frequently redirect users to other pages and websites'),
('Injection', 'A03:2021', 'Injection flaws such as SQL, NoSQL, OS, and LDAP injection occur when untrusted data is sent to an interpreter'),
('Broken Authentication', 'A07:2021', 'Application functions related to authentication and session management are often implemented incorrectly'),
('XML External Entities (XXE)', 'A04:2017', 'Many older or poorly configured XML processors evaluate external entity references within XML documents'),
('Broken Access Control', 'A01:2021', 'Restrictions on what authenticated users are allowed to do are often not properly enforced'),
('Security Logging and Monitoring Failures', 'A09:2021', 'Insufficient logging and monitoring, coupled with missing or ineffective integration with incident response'),
('Server-Side Request Forgery (SSRF)', 'A10:2021', 'SSRF flaws occur whenever a web application is fetching a remote resource without validating the user-supplied URL'),
('Command Injection', 'A03:2021', 'Command injection is an attack in which the goal is execution of arbitrary commands on the host operating system'),
('Path Traversal', 'A01:2021', 'Path traversal attacks aim to access files and directories that are stored outside the web root folder'),
('Local File Inclusion (LFI)', 'A03:2021', 'Local file inclusion is a type of vulnerability most often found in web applications'),
('Remote File Inclusion (RFI)', 'A03:2021', 'Remote file inclusion is a type of vulnerability most often found in web applications'),
('Buffer Overflow', 'A04:2017', 'Buffer overflow occurs when a program or process tries to store more data in a buffer than it was intended to hold'),
('Race Condition', 'A04:2017', 'Race conditions occur when multiple threads access shared data concurrently'),
('Insecure Cryptographic Storage', 'A02:2021', 'Many web applications do not properly protect sensitive data with appropriate encryption or hashing'),
('Insufficient Transport Layer Protection', 'A02:2021', 'Applications frequently fail to authenticate, encrypt, and protect the confidentiality and integrity of sensitive network traffic'),
('Information Disclosure', 'A01:2021', 'Information disclosure vulnerabilities occur when a system reveals sensitive information to unauthorized actors'),
('Denial of Service (DoS)', 'A04:2017', 'Denial of service attacks attempt to make a machine or network resource unavailable to its intended users'),
('Business Logic Flaws', 'A04:2017', 'Business logic flaws are ways of using the legitimate processing flow of an application in a way that results in a negative consequence'),
('Weak Session Management', 'A07:2021', 'Session management is the process of securing multiple requests to a web-based application or service from a user'),
('Insecure File Upload', 'A04:2017', 'File upload functionality is commonly associated with a number of security risks'),
('HTTP Response Splitting', 'A03:2021', 'HTTP response splitting occurs when user input is used to construct HTTP response headers');
