services:
  back-end:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - DB_POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --notify-keyspace-events Ex

volumes:
  postgres_data:
  redis_data:

networks:
  default:
      name: labs-net
      external: true
